export const WORD_POOL: string[] = [
  // Animals
  'TIGER', 'EAGLE', 'WHALE', 'SNAKE', 'HORSE', 'SHARK', 'PANDA', 'CAMEL',
  'BISON', 'CRANE', 'GOOSE', 'OTTER', 'RAVEN', 'ROBIN', 'TROUT', 'ZEBRA',
  'FALCON', 'PARROT', 'TURTLE', 'MONKEY', 'JAGUAR', 'LIZARD', 'BEETLE',
  'SPIDER', 'WALRUS', 'SALMON', 'BADGER', 'PIGEON', 'DONKEY', 'FERRET',
  'PENGUIN', 'DOLPHIN', 'CHEETAH', 'PANTHER', 'GORILLA', 'HAMSTER',
  'ALPACA', 'BOBCAT', 'COYOTE', 'FALCON', 'GOPHER', 'HERON', 'KOALA',
  'LEMUR', 'MOOSE', 'NEWT', 'OSPREY', 'PELICAN', 'QUAIL', 'STORK',
  'VIPER', 'WEASEL', 'IGUANA', 'JACKAL', 'MARMOT', 'NARWHAL', 'ORIOLE',
  'PYTHON', 'CONDOR', 'DINGO', 'ERMINE', 'FINCH', 'GROUSE', 'HYENA',
  'IMPALA', 'MANTIS', 'OYSTER', 'PUFFIN', 'RAPTOR', 'TOUCAN', 'SHRIMP',
  'HERMIT', 'LOCUST', 'MARLIN', 'MULLET', 'GIBBON', 'BELUGA', 'HORNET',
  'STARLING', 'MACKEREL', 'SCORPION', 'ANTELOPE', 'BLUEBIRD', 'CARDINAL',

  // Food & Drink
  'BREAD', 'GRAPE', 'LEMON', 'OLIVE', 'PEACH', 'PIZZA', 'SALAD', 'STEAK',
  'SUGAR', 'TOAST', 'CANDY', 'CREAM', 'JUICE', 'MELON', 'MANGO', 'PASTA',
  'CHEESE', 'COFFEE', 'COOKIE', 'GINGER', 'PEPPER', 'BANANA', 'CHERRY',
  'BUTTER', 'CARROT', 'POTATO', 'TOMATO', 'WAFFLE', 'PRETZEL', 'PANCAKE',
  'APPLE', 'BERRY', 'COCOA', 'DONUT', 'FLOUR', 'GUAVA', 'HONEY', 'KEBAB',
  'NACHO', 'ONION', 'PRAWN', 'RAMEN', 'SYRUP', 'THYME', 'WHEAT', 'YOGURT',
  'ALMOND', 'BISCUIT', 'CASHEW', 'CELERY', 'DUMPLING', 'FENNEL', 'GARLIC',
  'HAZELNUT', 'JASMINE', 'LETTUCE', 'MUFFIN', 'NOODLE', 'PAPAYA', 'QUINOA',
  'RADISH', 'SALMON', 'TURNIP', 'VANILLA', 'WALNUT', 'APRICOT', 'BROWNIE',
  'CARAMEL', 'CRACKER', 'CUSTARD', 'GRANOLA', 'LOBSTER', 'OYSTER', 'PUDDING',
  'SAFFRON', 'TRUFFLE', 'BAGUETTE', 'CINNAMON', 'ESPRESSO', 'HABANERO',

  // Nature
  'RIVER', 'OCEAN', 'STONE', 'CLOUD', 'STORM', 'BEACH', 'CORAL', 'FLAME',
  'FROST', 'GLOBE', 'JEWEL', 'MAPLE', 'PEARL', 'BROOK', 'CEDAR', 'CREEK',
  'FOREST', 'ISLAND', 'MEADOW', 'CANYON', 'DESERT', 'FLOWER', 'GARDEN',
  'JUNGLE', 'SUNSET', 'VALLEY', 'VOLCANO', 'CRYSTAL', 'GLACIER', 'RAINBOW',
  'AMBER', 'BLAZE', 'CREST', 'DRIFT', 'EMBER', 'FERN', 'GROVE', 'HAVEN',
  'IVORY', 'LUNAR', 'MARSH', 'NORTH', 'OASIS', 'PETAL', 'QUARTZ', 'RIDGE',
  'SHADE', 'THORN', 'VAPOR', 'WILLOW', 'BIRCH', 'BLOOM', 'DELTA', 'DUNE',
  'FLINT', 'GEYSER', 'LAGOON', 'LICHEN', 'MONSOON', 'NECTAR', 'RAPIDS',
  'SAVANNA', 'THICKET', 'TIMBER', 'TUNDRA', 'WETLAND', 'BLOSSOM', 'CASCADE',
  'CYPRESS', 'EROSION', 'GRANITE', 'HABITAT', 'MINERAL', 'BOULDER', 'CRIMSON',
  'HORIZON', 'TERRAIN', 'TSUNAMI', 'PLATEAU', 'CYCLONE', 'MONSOON',

  // Objects & Things
  'CROWN', 'CHAIR', 'CLOCK', 'PIANO', 'SWORD', 'TOWER', 'WHEEL',
  'ARROW', 'BRUSH', 'CANOE', 'COUCH', 'DRILL', 'FLUTE', 'KNIFE', 'LIGHT',
  'BRIDGE', 'CANDLE', 'CASTLE', 'GUITAR', 'HAMMER', 'LADDER', 'MIRROR',
  'PENCIL', 'ROCKET', 'SHIELD', 'TROPHY', 'LANTERN', 'COMPASS', 'DIAMOND',
  'BADGE', 'CHEST', 'CLASP', 'EASEL', 'FLASK', 'GLOBE', 'HINGE', 'LEVER',
  'MEDAL', 'PRISM', 'QUILT', 'RADAR', 'SIREN', 'VAULT', 'WRENCH', 'ANCHOR',
  'BANNER', 'BEACON', 'BUCKET', 'CARPET', 'CHISEL', 'DAGGER', 'FABRIC',
  'GADGET', 'HELMET', 'JERSEY', 'KETTLE', 'LOCKET', 'MAGNET', 'NEEDLE',
  'PADDLE', 'PLAQUE', 'RIBBON', 'SADDLE', 'SHOVEL', 'SOCKET', 'SWITCH',
  'TABLET', 'TURRET', 'VESSEL', 'WINCH', 'ZIPPER', 'CABINET', 'CURTAIN',
  'DOORWAY', 'GARMENT', 'PENDANT', 'WHISTLE', 'BLANKET', 'CHALICE',

  // Actions & Concepts
  'BRAVE', 'CHARM', 'DREAM', 'GRACE', 'HAPPY', 'MAGIC', 'PEACE', 'POWER',
  'QUICK', 'SMILE', 'SPARK', 'STORY', 'SWIFT', 'THINK', 'TRUTH', 'VALOR',
  'BRIGHT', 'CLEVER', 'ENERGY', 'GOLDEN', 'GENTLE', 'HUSTLE', 'LEGEND',
  'SPIRIT', 'WONDER', 'BALANCE', 'COURAGE', 'FREEDOM', 'JOURNEY', 'HARMONY',
  'AGILE', 'BLISS', 'CRAFT', 'DARING', 'FAITH', 'FOCUS', 'GLORY', 'HONOR',
  'IDEAL', 'JOLLY', 'KARMA', 'LOYAL', 'MERCY', 'NOBLE', 'PRIDE', 'QUEST',
  'REIGN', 'SAVVY', 'THRIVE', 'UNITE', 'VIGOR', 'WORTHY', 'ZEAL', 'ADEPT',
  'BLAZE', 'CANDOR', 'DEFT', 'EARNEST', 'FERVOR', 'GALLANT', 'HUMBLE',
  'INSPIRE', 'JUSTICE', 'KINDRED', 'LIBERTY', 'MARVEL', 'NURTURE', 'PASSION',
  'RESOLVE', 'SERENE', 'TRIUMPH', 'VENTURE', 'WISDOM', 'ACHIEVE', 'PROSPER',
  'RADIANT', 'SINCERE', 'TENACITY', 'VALIANT',

  // Science & Tech
  'LASER', 'RADAR', 'SOLAR', 'BRAIN', 'COMET', 'ORBIT',
  'QUARK', 'ROBOT', 'SONIC', 'ULTRA', 'XENON', 'OMEGA', 'ALPHA',
  'CARBON', 'GALAXY', 'PHOTON', 'PLASMA', 'PROTON', 'QUASAR',
  'SIGNAL', 'NEUTRON', 'NUCLEUS', 'QUANTUM', 'REACTOR', 'STELLAR',
  'ALLOY', 'ANODE', 'BADGE', 'BYTE', 'CABLE', 'DIODE', 'DRONE', 'FIBER',
  'FLUID', 'FORCE', 'FUSE', 'HELIX', 'IONIC', 'LENS', 'METAL', 'MOTOR',
  'NERVE', 'OXIDE', 'PIXEL', 'PULSE', 'RELAY', 'RIGID', 'SHAFT', 'STATIC',
  'SURGE', 'TITAN', 'VALVE', 'VOLTAGE', 'BINARY', 'CIPHER', 'DYNAMO',
  'FUSION', 'GENOME', 'HYBRID', 'ISOTOPE', 'LATTICE', 'MATRIX', 'NEBULA',
  'ORBITAL', 'POLYMER', 'REACTOR', 'SILICON', 'THERMAL', 'TURBINE', 'URANIUM',
  'VECTOR', 'CATALYST', 'ELECTRON', 'GRAPHENE', 'MAGNETIC', 'PARTICLE',

  // Places & Geography
  'FJORD', 'PLAZA', 'TRAIL', 'BASIN', 'CLIFF',
  'PLAIN', 'SHORE', 'SLOPE', 'SWAMP', 'HARBOR',
  'CAVERN', 'SUMMIT', 'ALLEY', 'ARENA', 'ATTIC', 'CABIN', 'CANAL',
  'COAST', 'DEPOT', 'FORUM', 'GLADE', 'GULCH', 'INLET', 'KNOLL',
  'LEDGE', 'MANOR', 'OASIS', 'POINT', 'RANCH', 'SHELF', 'TOWER',
  'WHARF', 'ARCADE', 'BAZAAR', 'CHAPEL', 'CITADEL', 'GORGE', 'HAMLET',
  'ISLAND', 'LAGOON', 'MARKET', 'PALACE', 'RAVINE', 'RESORT', 'TEMPLE',
  'TUNNEL', 'VILLAGE', 'TERRACE', 'CORRIDOR', 'FOUNTAIN', 'PAVILION',

  // Sports & Games
  'PITCH', 'SERVE', 'SCORE', 'MATCH', 'RALLY', 'TRACK', 'VAULT', 'DODGE',
  'BLOCK', 'CATCH', 'CHASE', 'FIELD', 'GOAL', 'MEDAL', 'POINT', 'RACE',
  'ROUND', 'SPRINT', 'THROW', 'ARENA', 'COACH', 'FINAL', 'LEAGUE',
  'PLAYER', 'RECORD', 'TACKLE', 'TROPHY', 'VOLLEY', 'DRIBBLE', 'HURDLE',
  'OFFENSE', 'PENALTY', 'PITCHER', 'REFEREE', 'STRIKER', 'WHISTLE',

  // Music & Arts
  'CHORD', 'DANCE', 'DRAMA', 'LYRIC', 'MURAL', 'OPERA', 'TEMPO', 'VERSE',
  'BALLET', 'CANVAS', 'CHORUS', 'FRESCO', 'MELODY', 'RHYTHM', 'SKETCH',
  'SONATA', 'STUDIO', 'ANTHEM', 'BALLAD', 'ENCORE', 'PALETTE', 'PRELUDE',
  'QUARTET', 'RECITAL', 'SOPRANO', 'CONCERT', 'GALLERY', 'MUSICAL', 'OVERTURE',

  // Weather & Seasons
  'BLIZZARD', 'BREEZE', 'DRIZZLE', 'FLURRY', 'GUST', 'HAZE', 'MIST',
  'SLEET', 'SQUALL', 'THAW', 'FROST', 'HUMID', 'FOGGY', 'SUNNY', 'WINDY',
  'AUTUMN', 'SPRING', 'SUMMER', 'WINTER', 'ECLIPSE', 'SOLSTICE',

  // Clothing & Fabric
  'BOOTS', 'CLOAK', 'DENIM', 'LINEN', 'PLAID', 'SCARF', 'SHAWL', 'SILK',
  'SUEDE', 'TWEED', 'VELVET', 'BONNET', 'BUCKLE', 'COTTON', 'FLEECE',
  'JACKET', 'MITTEN', 'SANDAL', 'SATIN', 'STITCH', 'THREAD', 'ZIPPER',

  // Body & Health
  'BRAIN', 'HEART', 'JOINT', 'LIVER', 'MUSCLE', 'NERVE', 'PULSE', 'SPINE',
  'ELBOW', 'FEMUR', 'GLAND', 'KNEE', 'ORGAN', 'SKULL', 'TENDON', 'TISSUE',
  'VESSEL', 'BICEP', 'FIBER', 'LYMPH', 'PELVIS', 'REFLEX', 'TORSO',

  // Household
  'BASIN', 'BLIND', 'BRICK', 'CEDAR', 'DRAIN', 'FENCE', 'GROUT', 'HINGE',
  'KNOB', 'LATCH', 'MORTAR', 'PANEL', 'SHELF', 'SLATE', 'STAIR', 'VALVE',
  'CLOSET', 'FAUCET', 'GARAGE', 'GUTTER', 'MANTLE', 'PANTRY', 'PILLAR',
  'PLASTER', 'RAFTER', 'SHINGLE', 'CABINET', 'CHIMNEY', 'HALLWAY',

  // Travel & Transport
  'CABIN', 'CARGO', 'FERRY', 'KAYAK', 'ROUTE', 'YACHT', 'BARGE', 'DEPOT',
  'GUIDE', 'HARBOR', 'JETTY', 'LINER', 'PILOT', 'STERN', 'VOYAGE', 'CRUISE',
  'ENGINE', 'FLIGHT', 'RUNWAY', 'STATION', 'TRANSIT', 'CARAVAN', 'JOURNEY',

  // Colors & Materials
  'AZURE', 'CORAL', 'IVORY', 'KHAKI', 'LILAC', 'MAUVE', 'OCHRE', 'PEARL',
  'ROUGE', 'SEPIA', 'TAUPE', 'BEIGE', 'BRONZE', 'COBALT', 'COPPER', 'INDIGO',
  'MAROON', 'PEWTER', 'RUSTIC', 'SCARLET', 'CRIMSON', 'EMERALD', 'MAGENTA',

  // Professions
  'BAKER', 'CLERK', 'JUDGE', 'MASON', 'NURSE', 'PILOT', 'SMITH', 'TUTOR',
  'ACTOR', 'CHIEF', 'GUARD', 'MAYOR', 'SCOUT', 'TAILOR', 'AUTHOR', 'BANKER',
  'ARTIST', 'CAPTAIN', 'DENTIST', 'FARMER', 'LAWYER', 'RANGER', 'SCHOLAR',
  'SURGEON', 'WELDER', 'BUTCHER', 'COBBLER', 'FLORIST', 'PLUMBER',
];
